### PR TITLE
initial commit anomaly detection with gradient guidance

### PR DESCRIPTION
**Pull request by JuliaWolleb**
Draft pull request for issue 155: add tutorial about diffusion models for medical anomaly detection using gradient guidance.

### CODE REVIEW

**Comment by JuliaWolleb** [comment]
Hi @Warvito 
I included all changes you suggested, now this branch should be up-to-date. What can/should I do such that you can merge it to the main branch?
Ah, and one thing: my tutorial is now in the folder _tutorials/generative/anomaly_detection/classifier_guidance_anomalydetection/..._ . Should I move them one folder up?

**Comment by Warvito** [comment]
> Hi @Warvito I included all changes you suggested, now this branch should be up-to-date. What can/should I do such that you can merge it to the main branch?

Hi @JuliaWolleb . Thank you for the changes! It looks great. I saw that you merged the main into the branch as expected, but the branch still changing a few things that it should not. Do you mind if I add a commit to fix that?

>  Ah, and one thing: my tutorial is now in the folder _tutorials/generative/anomaly_detection/classifier_guidance_anomalydetection/..._ . Should I move them one folder up?

Yes, I guess it will be okay to have the 3 methods in the `tutorials/generative/anomaly_detection`

**Comment by JuliaWolleb** [comment]
Hi @Warvito 


> 

Sure, just add any commit to fix the issues.

**Review by Warvito — APPROVED** [review]
Thanks for adding this tutorial @JuliaWolleb ! It is looking great. I fixed the files that it was complaining about, moved the tutorial one folder up and it is ready for merge ^^

**Pull request merged**
